### ISSUE TITLE
Crash before title screen on Linux

### ISSUE THREAD

**Issue by Jayman2000** [AgitationSkeleton/open_fortress#30]
On Linux, Open Fortress crashes before the title screen is able to finish loading.

#### Steps to Reproduce
1. Clone this repository into the sourcemods directory.
2. Start/restart Steam.
3. Launch Open Fortress.
4. Wait for the intro video to finish, or skip it.

#### Expected Result
After a medium loading screen, Open Fortress finishes loading and the title screen appears. When running the game under Windows, this is the actual result.

#### Actual Result
After a short loading screen, an error message pops up that says:
>Could not load library client. Try restarting. If that doesn't work, verify the cache.

Clicking "OK" closes the game. Restarting the game does not fix the problem. Verifying the integrity of the tool files for Source SDK Base 2013 Multiplayer also does not fix the problem.

**Comment by occune** [comment]
can confirm on Debian 10

**Comment by ThatGeekZen** [comment]
Game crashes on Fedora 30 as well. 
"Invalid or corrupt background texture materials/console/background01_widescreen.vtf"

**Comment by Chrissy573** [comment]
The new menu (GameUI) currently has issues mounting files because of lower/uppercase differences in the code. They will soon be fixed and I hope to have a Debian distribution running to ensure these issues won't remain for weeks. Apologies.

@ThatGeekZen your issue is related with how the mod was downloaded. git-lfs is required to obtain the material files, including background01_widescreen (which hasn't been fully cloned in your case).

**Comment by Nopey** [comment]
This has little to do with gameui itself, and is just kai accidentally reverting my VPC changes from way back.
This occurs because of dynamic linking. Running `ldd` on the games `client.so` will reveal its trying to link to libdiscord-rpc.so
I fixed this and then got lost in the gameui changes, forgetting to push the fix to linking.
This should be fixed within the hour

**Comment by Nopey** [comment]
This should now be fixed. Please check if commit 2530dc30509a3a18c5577b0f082c2f8e00eca33b fixes this.

**Comment by Jayman2000** [comment]
I can confirm that this issue is fixed. Thank you!
